# Generated by Django 3.2.7 on 2021-11-20 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_institue'),
        ('jobs', '0001_initial'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cgpa',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='graduation_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='institute_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.institue'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_application',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
        migrations.AlterField(
            model_name='application',
            name='process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.process'),
        ),
    ]
