# Generated by Django 3.2.7 on 2021-11-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211120_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rounds',
            old_name='apptitude',
            new_name='aptitude',
        ),
        migrations.AddField(
            model_name='application',
            name='ans',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.TextField(null=True),
        ),
    ]
