# Generated by Django 3.2.7 on 2021-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('phone_no', models.BigIntegerField()),
                ('emailID', models.EmailField(max_length=70)),
                ('nationality', models.CharField(max_length=70)),
                ('insititue', models.CharField(max_length=70)),
                ('degree', models.CharField(max_length=70)),
                ('graduation_year', models.DateField()),
            ],
        ),
    ]
