# Generated by Django 3.2.7 on 2021-11-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='insititue',
            new_name='institute',
        ),
    ]
