# Generated by Django 3.2.7 on 2021-11-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20211120_1525'),
        ('applicant', '0004_auto_20211120_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='institue',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='institute',
            old_name='institue_id',
            new_name='institute_id',
        ),
    ]
