# Generated by Django 3.1.2 on 2021-11-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_auto_20211120_1642'),
        ('applicant', '0004_auto_20211120_1358'),
    ]

    operations = [
    ]
