# Generated by Django 3.1.2 on 2021-10-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant',
            new_name='ApplicantCredentials',
        ),
    ]
