# Generated by Django 3.1.2 on 2021-10-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211015_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantSignedUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('emailID', models.EmailField(max_length=70)),
                ('newPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='ApplicantCredentials',
            new_name='ApplicantLoggedIn',
        ),
    ]
