# Generated by Django 3.2.7 on 2021-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='graduation_year',
            field=models.DateField(),
        ),
    ]
