# Generated by Django 3.2.7 on 2021-11-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_applicant_graduation_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applicant',
        ),
    ]
